version: '2'
services:
    wildfly:
        build: ./images/wildfly
        links:
            - mysql:db
        ports:
            - "9090:8080"
            - "9990:9990"
            - "8787:8787"
    mysql:
        build: ./images/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=adminpw
        ports:
            - "3307:3306"
